apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerated
  labels:
    project: roboshop
    environment: dev
    purpose: poc
spec:
  containers:
  - name: nginx # container
    image: nginx #by default it'll get gtom docker hub
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"